## Borrower reliability study

The customer is the credit department of the bank. It is necessary to find out whether the marital status and the number of children of the client affect the fact of repaying the loan on time. Input data from the bank - statistics on the solvency of customers.

The results of the study will be taken into account when building a **credit scoring** model - a special system that evaluates the ability of a potential borrower to repay a loan to a bank.

### Step 1. Open the data file and examine the general information.

In [1]:
import pandas as pd
data = pd.read_csv('/datasets/data.csv')
print(data)
data.info()
data.dtypes
data

       children  days_employed  dob_years education  education_id  \
0             1   -8437.673028         42    высшее             0   
1             1   -4024.803754         36   среднее             1   
2             0   -5623.422610         33   Среднее             1   
3             3   -4124.747207         32   среднее             1   
4             0  340266.072047         53   среднее             1   
...         ...            ...        ...       ...           ...   
21520         1   -4529.316663         43   среднее             1   
21521         0  343937.404131         67   среднее             1   
21522         1   -2113.346888         38   среднее             1   
21523         3   -3112.481705         38   среднее             1   
21524         2   -1984.507589         40   среднее             1   

          family_status  family_status_id gender income_type  debt  \
0       женат / замужем                 0      F   сотрудник     0   
1       женат / замужем        

children  days_employed  dob_years education  education_id  \
0             1   -8437.673028         42    высшее             0   
1             1   -4024.803754         36   среднее             1   
2             0   -5623.422610         33   Среднее             1   
3             3   -4124.747207         32   среднее             1   
4             0  340266.072047         53   среднее             1   
...         ...            ...        ...       ...           ...   
21520         1   -4529.316663         43   среднее             1   
21521         0  343937.404131         67   среднее             1   
21522         1   -2113.346888         38   среднее             1   
21523         3   -3112.481705         38   среднее             1   
21524         2   -1984.507589         40   среднее             1   

          family_status  family_status_id gender income_type  debt  \
0       женат / замужем                 0      F   сотрудник     0   
1       женат / замужем                 0      F   сотрудник     0   
2       женат / замужем                 0      M   сотрудник     0   
3       женат / замужем                 0      M   сотрудник     0   
4      гражданский брак                 1      F   пенсионер     0   
...                 ...               ...    ...         ...   ...   
21520  гражданский брак                 1      F   компаньон     0   
21521   женат / замужем                 0      F   пенсионер     0   
21522  гражданский брак                 1      M   сотрудник     1   
21523   женат / замужем                 0      M   сотрудник     1   
21524   женат / замужем                 0      F   сотрудник     0   

        total_income                       purpose  
0      253875.639453                 покупка жилья  
1      112080.014102       приобретение автомобиля  
2      145885.952297                 покупка жилья  
3      267628.550329    дополнительное образование  
4      158616.077870               сыграть свадьбу  
...              ...                           ...  
21520  224791.862382             операции с жильем  
21521  155999.806512          сделка с автомобилем  
21522   89672.561153                  недвижимость  
21523  244093.050500  на покупку своего автомобиля  
21524   82047.418899         на покупку автомобиля  

[21525 rows x 12 columns]

### Conclusion

***Data type specified incorrectly in columns 'education_id', 'family_status_id', 'debt'
Different case in the education column
Negative values in the days_employed column
Lemmas in the values in the purpose column***




### Step 2. Data preprocessing

### Pass processing

In [2]:
nan = data[data['total_income'].isnull()].head(20) # Search columns with NaN
data.loc[data['children'] < 0, 'children'] = data['children'] * -1 # Replace all negative values with positive ones in the 'days_employed' column
data.loc[data['days_employed'] < 0, 'days_employed'] = data['days_employed'] * -1
data.loc[data['children'] == 20 , 'children'] = 2 # Replacing the value 20 with 2
days_employed_avg = data['days_employed'].median() # Median 
total_income_avg = data['total_income'].mean() # Mean
dob_years_avg = data['dob_years'].mean() # Median
data['days_employed'] = data['days_employed'].fillna(value = days_employed_avg) # replacing missing values with days_employed_avg
data['total_income'] = data['total_income'].fillna(value = total_income_avg) # replacing missing values with total_income_avg
data['dob_years'] = data['dob_years'].replace(0, dob_years_avg) # replacing values with total_income_avg

### Conclusion

***Missing values were found in columns 'total_income' and 'days_employed'
Perhaps people did not indicate their income and hours of work, although some of them wrote that they are currently working.
There were also negative values in the 'days_employed' column. Perhaps this error appeared when unloading data
I filled in the gaps in the first column using the median. Since the values differed greatly
In the second, using the average value.***

### Data type replacement

In [3]:
data['total_income'] = data['total_income'].astype('int') # replacing the real data type with an integer in the total_income column
data['days_employed'] = data['days_employed'].astype('int') # replace the real data type with an integer in the days_employed column
data.loc[data['income_type'] == 'предприниматель', 'income_type'] = 'компаньон' # replacement value
data['dob_years'] = data['dob_years'].astype('int')
print(data)


       children  days_employed  dob_years education  education_id  \
0             1           8437         42    высшее             0   
1             1           4024         36   среднее             1   
2             0           5623         33   Среднее             1   
3             3           4124         32   среднее             1   
4             0         340266         53   среднее             1   
...         ...            ...        ...       ...           ...   
21520         1           4529         43   среднее             1   
21521         0         343937         67   среднее             1   
21522         1           2113         38   среднее             1   
21523         3           3112         38   среднее             1   
21524         2           1984         40   среднее             1   

          family_status  family_status_id gender income_type  debt  \
0       женат / замужем                 0      F   сотрудник     0   
1       женат / замужем        

### Conclusion

**I chose the method as it suits best in this case. There is 1 more method to_numeric(), but it converts strings to floats.**


### Duplicate Handling

In [4]:
data.index[data.income_type == 17]

Int64Index([], dtype='int64')

In [5]:
data.income_type[0]

'сотрудник'

In [6]:
print(data['education'].value_counts()) # find outliers
    # Removing outliers
data = data.drop(data[data.income_type == 'в декрете'].index) 
data = data.drop(data[data.income_type == 'безработный'].index)
data = data.drop(data[data.income_type == 'студент'].index)
data = data.drop(data[data.children == 5].index)
data = data.drop(data[data.education == 'ученая степень'].index)
data = data.drop(data[data.gender == 'XNA'].index)



среднее                13750
высшее                  4718
СРЕДНЕЕ                  772
Среднее                  711
неоконченное высшее      668
ВЫСШЕЕ                   274
Высшее                   268
начальное                250
Неоконченное высшее       47
НЕОКОНЧЕННОЕ ВЫСШЕЕ       29
НАЧАЛЬНОЕ                 17
Начальное                 15
ученая степень             4
Ученая степень             1
УЧЕНАЯ СТЕПЕНЬ             1
Name: education, dtype: int64


In [7]:
if 'i' in 'in':
    print(5)

5


In [8]:
data['education'] = data['education'].str.lower() # All lines to the same register
data = data.drop_duplicates().reset_index(drop=True) # remove duplicates and reset indexes

### Conclusion

**There were not many duplicates in the table, but there were words with different case, and a few outliers.
I replaced the entrepreneur with a companion, deleted everything else**
Used the drop_duplicates() method
Perhaps duplicates appeared due to a software error.

### Lemmatization

In [9]:
from pymystem3 import Mystem #import the library
m = Mystem()
purpose_lem = [] # create a list
for i in data['purpose']:
    lemmas = m.lemmatize(i) # Lemmatization
    purpose_lem.append(lemmas) # add the resulting values to the list
    
data['purpose_lem'] = purpose_lem # add a new column to our dataframe
print(data['purpose_lem'])


0                             [покупка,  , жилье, \n]
1                   [приобретение,  , автомобиль, \n]
2                             [покупка,  , жилье, \n]
3                [дополнительный,  , образование, \n]
4                           [сыграть,  , свадьба, \n]
                             ...                     
21431                  [операция,  , с,  , жилье, \n]
21432               [сделка,  , с,  , автомобиль, \n]
21433                              [недвижимость, \n]
21434    [на,  , покупка,  , свой,  , автомобиль, \n]
21435             [на,  , покупка,  , автомобиль, \n]
Name: purpose_lem, Length: 21436, dtype: object


### Вывод

In [10]:
from collections import Counter # the Counter container from the collections module.
lems = '' # create an empty string
for lem in data['purpose_lem']: # Breaking the date set into lists
    lems += ' '.join(lem) # We blind 
lems = lems.split() # Create a string
print(Counter(lems))

Counter({'недвижимость': 6344, 'покупка': 5890, 'жилье': 4455, 'автомобиль': 4303, 'образование': 4011, 'с': 2915, 'операция': 2601, 'свадьба': 2323, 'свой': 2228, 'на': 2220, 'строительство': 1877, 'высокий': 1372, 'получение': 1314, 'коммерческий': 1310, 'для': 1288, 'жилой': 1229, 'сделка': 940, 'дополнительный': 906, 'заниматься': 902, 'проведение': 767, 'сыграть': 765, 'сдача': 650, 'семья': 638, 'собственный': 634, 'со': 626, 'ремонт': 606, 'подержанный': 485, 'подержать': 478, 'приобретение': 461, 'профильный': 436})


*** Of all the categories, I have identified 4 main ones (real estate, housing, car, education, wedding) ***

### Data categorization

In [14]:
# the main thing was whether the debts, and then any column can be added to this
children_dict = data[['children', 'debt']]
family_status_dict = data[['family_status', 'debt']]
total_income_dict = data[['total_income', 'debt']]
purpose_dict = data[['purpose', 'debt']]

# Added categories
children_total_income = data[['children', 'total_income']] 
income = data[['income_type', 'total_income']]
income_group_dict = data[['income_group', 'debt']]
status_dict = data[['family_status', 'dob_years']]

### Conclusion

***I have highlighted the main categories that I needed in subsequent assignments***


### Step 3: Answer the questions

- Is there a relationship between having children and repaying the loan on time?

In [15]:
children_dict = data[['children', 'debt']] # take only the necessary columns from the dataframe
print(children_dict.groupby('children').mean().sort_values('debt',ascending=False)) # group by children and find the average debt

              debt
children          
4         0.097561
2         0.094499
1         0.091490
3         0.082067
0         0.075465


### Conclusion

***There is. Families without children repay loans better, while families with many children repay debts worse. I think this is due to the fact that a child takes a lot of time and money. It turns out that someone who spends, but does not earn, appears in the family. Also, parents cannot earn the same as without children, because they need to be educated.***



- Is there a relationship between marital status and loan repayment on time?

In [16]:
family_status_dict = data[['family_status', 'debt']] # take only the necessary columns from the dataframe
print(family_status_dict.groupby('family_status').mean().sort_values('debt',ascending=False)) # group by family_status and find the average debt

                           debt
family_status                  
Не женат / не замужем  0.097544
гражданский брак       0.093562
женат / замужем        0.075363
в разводе              0.071189
вдовец / вдова         0.065693


### Conclusion

***Those who are not married and not married, as well as in a civil marriage, are most often young, and they do not understand how loans work in general, since there is no financial literacy, or it is at a minimum level, therefore they return loans less often than anyone. It turns out the category of married / married and divorced is mostly middle-aged people and they are more responsible. In the widower / widow category, the most common are the elderly, they almost always give money away.***

In [17]:
# In support of my theory, you can analyze the data
status_dict = data[['family_status', 'dob_years']] # take only the necessary columns from the dataframe
print(status_dict.groupby('family_status').mean().sort_values('dob_years',ascending=False)) # group by family_status and find the average dob_years

                       dob_years
family_status                   
вдовец / вдова         56.727842
в разводе              45.885260
женат / замужем        43.720045
гражданский брак       42.292501
Не женат / не замужем  38.614454


- Is there a relationship between the level of income and repayment of the loan on time?

In [18]:
data['total_income'].quantile([0.25, 0.5, 0.75, 1]) #50% quantile == median


0.25     107629.00
0.50     156033.50
0.75     195759.75
1.00    2265604.00
Name: total_income, dtype: float64

In [19]:
"""
Returns the income level by the value of total_income using the rules:

- 'poor' if income <= 50000

- 'poor' if 50000 <= income <= 150000 inclusive

- 'middle class' with a value of 150000 <= income <= 400000 inclusive

- 'rich' in all other cases
"""

def income_group(row): 

    income = row['total_income']


    if income <= 107629.00:
        return 'нищите'
    

    if 156033.50 <= income <= 195759.75:


        return 'бедные'
    
    if 195759.75 <= income <= 2265604.00:


        return 'средний класс'

    return 'богатые'
data['income_group'] = data.apply(income_group, axis=1) # create a column with the received values

income_group_dict = data[['income_group', 'debt']] # take only the necessary columns from the dataframe
print(income_group_dict.groupby('income_group').mean().sort_values('debt',ascending=False)) # group by income_group and find the average debt

                   debt
income_group           
богатые        0.087330
бедные         0.086397
нищите         0.079306
средний класс  0.071469


In [20]:
#data['total_income'].quantile([0.25, 0.5, 0.75, 1]) #50% quantile == median

income = data[['income_type', 'total_income']] # take only the necessary columns from the dataframe
print(income.groupby('income_type').mean().sort_values('total_income',ascending=False)) # group by income_type and find the average total_income

              total_income
income_type               
компаньон    199021.245814
госслужащий  170623.097595
сотрудник    161952.148880
пенсионер    140150.895507


### Conclusion

***The rich return the loan less often than the poor and even the poor. Perhaps because entrepreneurs earn a lot of money, and a business loan is usually quite large and it is almost impossible to repay it if the business goes bankrupt. The poor most often simply do not have money to return, but the poor are mostly pensioners. They are more responsible. The middle class earns enough to return the money to the bank and most often they have a stable job.***

- How do different purposes of the loan affect its repayment on time?

In [21]:
"""
Returns the loan type given the value of purpose_lem using the rules:

- 'real estate' with the meaning ('housing' in income) or ('real estate' in income)

- 'car' when 'car' in income

- 'wedding' when 'wedding' in income

- 'education' with the value 'education' in income:

- 'not clear' in all other cases
"""
def purpose_group(row):
    income = row['purpose_lem']
    if ('жилье' in income) or ('недвижимость' in income):
        return 'недвижимость'
    
    if 'автомобиль' in income:


        return 'автомобиль'

    if 'свадьба' in income:


        return 'свадьба'

    if 'образование' in income:


        return 'образование'
    
    else:

        return 'не понятно'

        
data['purpose_group'] = data.apply(purpose_group, axis=1) # create a column with the received values
purpose_group_dict = data[['purpose_group', 'debt']] # take only the necessary columns from the dataframe
print(purpose_group_dict.groupby('purpose_group').mean().sort_values('debt',ascending=False)) # group by income_group and find the average debt

                   debt
purpose_group          
автомобиль     0.093423
образование    0.092246
свадьба        0.080069
недвижимость   0.072322


### Conclusion

***A car loan is the least likely to be returned because this asset quickly loses its value and requires quite a large investment, and many do not think about it when buying. With education, it seems to me that people most often find it difficult to work and study. For a wedding, money is most often given and the family can pay off the loan together, it's not much easier than doing it alone, and real estate is the thing for which if you don't pay, they'll just be kicked out, so people try to find money anywhere to pay off the mortgage***


### Step 4. General conclusion

On average, customers are about equally likely not to return money.
The level of income affects this the most. Another important feature is the purpose of the loan, marital status and the number of children.
Families without children repay loans better, while families with many children repay debts worse. Those who are not married and not married, as well as in a civil marriage, most often do not give loans, but a widower / widow most often gives money. The rich return loans less often than the poor and even the poor. The middle class earns enough to pay back the bank and usually they have stable jobs, so they are the most reliable borrowers in this category. And the riskiest category of credit is a car and education, but the most protected is real estate.
Portrait of the most reliable borrower - He has no children, is a widower, with earnings from 195759.75 to 2265604 and trying to get a loan for real estate.
Portrait of the most risky borrower - He has 4 children, is not married or in a civil marriage, and with an income of 2265604 and he is trying to take out a loan for a car or education.

In [22]:
#The most reliable borrowers
print(data[(data['children'] == 0) & (data['family_status'] == 'вдовец / вдова') & ( data['total_income'] <= 2265604) & ( data['total_income'] >= 195759.75) & ( data['purpose_group'] == 'недвижимость')].head(60))

       children  days_employed  dob_years            education  education_id  \
767           0         367177         59              среднее             1   
902           0           1826         66              среднее             1   
1383          0         353802         37              среднее             1   
1387          0           1985         56               высшее             0   
1455          0         384834         58               высшее             0   
1915          0         373836         67               высшее             0   
1925          0         378929         65              среднее             1   
2466          0           1160         62               высшее             0   
2649          0         364303         62              среднее             1   
2894          0           1272         58              среднее             1   
3023          0            367         44               высшее             0   
3075          0           1554         5

In [23]:
# The most risky borrowers
print(data[(data['children'] == 4) & (data['family_status'] == 'Не женат / не замужем') & ( data['total_income'] >= 2265604) & ( data['purpose_group'] == 'автомобиль')].head(60))

Empty DataFrame
Columns: [children, days_employed, dob_years, education, education_id, family_status, family_status_id, gender, income_type, debt, total_income, purpose, purpose_lem, income_group, purpose_group]
Index: []
